---
title: "Untitled"
author: "Yash Gimonkar"
date: "2024-03-02"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{python}
!pip install scipy
!pip install matplotlib
!pip install rasterio
```

```{python}
import numpy as np
import matplotlib.pyplot as plt

from scipy.ndimage import gaussian_filter

import rasterio
from rasterio.transform import from_origin
```

```{r}
library(reticulate)
library(terra)
library(raster)
```

```{r}
ras_stack <- stack("C:/Users/yashg/OneDrive - University of Tasmania/Detecting change project/Data/SO_CPR_yr_month_sst_stack.gri")

ras_stack <- aggregate(ras_stack, fact = 4)
```

```{python echo=TRUE}
# Define raster dimensions based on ras_stack
rows = 62
cols = 214

# Define spatial extent
xmin, xmax = 53, 160
ymin, ymax = -69, -38

# Define resolution
resolution = (0.5, 0.5)

# Generate coordinates grid
x_coords = np.linspace(xmin, xmax, cols)
y_coords = np.linspace(ymin, ymax, rows)
X, Y = np.meshgrid(x_coords, y_coords)

# Generate random values for the raster
random_values = np.random.rand(rows, cols)

# Apply spatial filter (Gaussian blur) to introduce spatial correlation
sigma = 12  # Standard deviation for Gaussian filter
correlated_values = gaussian_filter(random_values, sigma=sigma)

# Define output file path
output_path = "C:/Users/yashg/OneDrive - University of Tasmania/Detecting change project/Data/Chapter 1/Simulation/Multiple runs/correlated_dummy_raster.tif"

# Write the correlated values to a GeoTIFF file
with rasterio.open(
    output_path,
    'w',
    driver='GTiff',
    height=rows,
    width=cols,
    count=1,
    dtype=correlated_values.dtype,
    crs='+proj=longlat +datum=WGS84 +no_defs',
    transform=from_origin(xmin, ymax, resolution[0], resolution[1])
) as dst:
    dst.write(correlated_values, 1)
```

```{r}
ras_corr<- rast("correlated_dummy_raster.tif")

plot(ras_corr)
plot(rast(ras_stack$Jan.1997))
```

```{r}
ras_corr
ras_stack$Jan.1997
```
